import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Navbar2 from "./components/navbar2/Navbar2";
import Footer from "./components/footer/page";
import AuthProvider from "./Providers";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Omegle",
  description: "Generated by create Omegle",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>
    
      <AuthProvider>
                {children}
      </AuthProvider>
    </body>
  </html>
  );
}
